"""add_currency_to_user_master

Revision ID: 8f5cf9cf6900
Revises: 024dfe776d88
Create Date: 2026-06-26 19:52:26.236498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5cf9cf6900'
down_revision: Union[str, Sequence[str], None] = '024dfe776d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_master', sa.Column('currency', sa.String(length=10), server_default=sa.text("'RUB'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_master', 'currency')
    # ### end Alembic commands ###
