"""add_slots_and_buffers

Revision ID: 97671cabe0cb
Revises: 8f5cf9cf6900
Create Date: 2026-06-27 06:46:40.323889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97671cabe0cb'
down_revision: Union[str, Sequence[str], None] = '8f5cf9cf6900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column('user_master', sa.Column('slot_step', sa.Integer(), nullable=True))
    op.add_column('user_master', sa.Column('client_buffer', sa.Integer(), nullable=True))
    op.add_column('user_master', sa.Column('master_buffer', sa.Integer(), nullable=True))

    op.execute("UPDATE user_master SET slot_step = 30 WHERE slot_step IS NULL")
    op.execute("UPDATE user_master SET client_buffer = 360 WHERE client_buffer IS NULL")
    op.execute("UPDATE user_master SET master_buffer = 120 WHERE master_buffer IS NULL")

    op.alter_column('user_master', 'slot_step', nullable=False)
    op.alter_column('user_master', 'client_buffer', nullable=False)
    op.alter_column('user_master', 'master_buffer', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_master', 'master_buffer')
    op.drop_column('user_master', 'client_buffer')
    op.drop_column('user_master', 'slot_step')
    # ### end Alembic commands ###
